version: "3.5"
networks:
  dev-network:

services:
  db:
    image: mongo:4.0
    restart: unless-stopped
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - 27021:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
    networks:
      - dev-network
  redis:
    image: redis:6.0-alpine
    ports:
      - 6390:6379
    networks:
      - dev-network
  kafka-ui:
    image: provectuslabs/kafka-ui
    ports:
      - 8080:8080
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181

  zookeeper:
    image: zookeeper:3.4.13
    ports:
      - 2181:2181

  kafka:
    image: confluentinc/cp-kafka:5.3.1
    ports:
      - 9093:9093
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,PLAINTEXT://0.0.0.0:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,PLAINTEXT://localhost:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
    depends_on:
      - zookeeper
  www:
    image: rolfwessels/coredocker-dashboard:alpha
    links:
      - src
    environment:
      - API_URL=http://localhost:5000
    ports:
      - 84:80

  src:
    depends_on:
      - redis
      - db      - kafka
    container_name: core-docker
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ".:/CoreDocker"
      - "./.aws:/root/.aws"
      #find src* | grep  '/bin$' | sed 's/^/ - CoreDocker\//'
      - /CoreDocker/src/CoreDocker.Api/bin
      - /CoreDocker/src/CoreDocker.Api.Lambda/bin
      - /CoreDocker/src/CoreDocker.Core/bin
      - /CoreDocker/src/CoreDocker.Dal/bin
      - /CoreDocker/src/CoreDocker.Dal.MongoDb/bin
      - /CoreDocker/src/CoreDocker.Sdk/bin
      - /CoreDocker/src/CoreDocker.Shared/bin
      - /CoreDocker/src/CoreDocker.Utilities/bin
      - /CoreDocker/test/CoreDocker.Api.Tests/bin
      - /CoreDocker/test/CoreDocker.Core.Tests/bin
      - /CoreDocker/test/CoreDocker.Utilities.Tests/bin
      #find src* | grep  '/obj$' | sed 's/^/ - /CoreDocker\//'
      - /CoreDocker/src/CoreDocker.Api/obj
      - /CoreDocker/src/CoreDocker.Api.Lambda/obj
      - /CoreDocker/src/CoreDocker.Core/obj
      - /CoreDocker/src/CoreDocker.Dal/obj
      - /CoreDocker/src/CoreDocker.Dal.MongoDb/obj
      - /CoreDocker/src/CoreDocker.Sdk/obj
      - /CoreDocker/src/CoreDocker.Shared/obj
      - /CoreDocker/src/CoreDocker.Utilities/obj
      - /CoreDocker/test/CoreDocker.Api.Tests/obj
      - /CoreDocker/test/CoreDocker.Core.Tests/obj
      - /CoreDocker/test/CoreDocker.Utilities.Tests/obj

    environment:
      - DOTNET_ENVIRONMENT=Development
      - MongoConnection=mongodb://db:27017/core-docker
      - MongoDatabase=core-docker
      - RedisHost=redis
      - App__HostUrl=http://localhost:5000
      - OpenId__Origins=http://localhost:5000,http://localhost:84,http://localhost:3000
    ports:
      - 5000:5000
    entrypoint: top -b
    logging:
      driver: none
    networks:
      - dev-network
