version: '3'
services:
    db:
        image: mongo:latest
        container_name: "db"
        restart: unless-stopped
        environment:
        - MONGO_DATA_DIR=/data/db
        - MONGO_LOG_DIR=/dev/null
        ports:
        - 27020:27017
        command: mongod --smallfiles --logpath=/dev/null # --quiet

    web:
        image: rolfwessels/coredocker:latest
        deploy:
        restart: unless-stopped
        links:
        - db:db
        environment:
        - MongoConnection=mongodb://db:27017/CoreDocker
        - MongoDatabase=CoreDocker
        - Serilog__WriteTo__0__Args__pathFormat=/data/logs/coredocker.api.{Date}.log
        volumes:
        - /data/logs:/data/logs
        ports:
        - 5000:5000
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:5000/api/ping/hc"]
            interval: 30s
            timeout: 10s
            retries: 3
        labels:
        - "traefik.enable=true"
        - "traefik.port=5000"
        - "traefik.frontend.rule=Host:dev-coredocker.mediaserver.wessels.online"
networks:
 default:
   external:
      name: mediaserver_default

