name: .NET

on:
  push:
    branches:
      - master
      - feature/move-github-actions
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Allow make commands
        run: touch /.dockerenv
      - name: Test
        run: make test
