name: .NET

on:
  push:
    branches:
      - master
      - feature/move-github-actions
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Setup Redis
        uses: shogo82148/actions-setup-redis@v1
        with:
          redis-version: "6.x"
      - name: Test
        run: make test
